eksctl create cluster /
--name MySQLCluster /
--region eu-west-2 /
--nodegroup-name DemoNodes /
--nodes 2 /
--nodes-min 2 /
--nodes-max 3 /
--node-type t3.medium /
--with-oidc /
--ssh-access /
--ssh-public-key /home/ubuntu/.ssh/id_rsa.pub /
--managed
